= 分支模型

首先，为什么要有分支模型？或者说，我们现在的workflow有什么问题？相信已经被各种巨型分支合并、
混乱地版本发布、各种线上hotfix折磨的苦不堪言的各位多少都能回答一二了。

再讲我们的问题之前，先讲一讲我个人对于分支模型的理解。

== 组成分支模型的维度

=== 在哪开发？

顾名思义，就是各位平常代码提交到主线还是分支。根据这一点，分支模型分为了主线开发和分支开发两大类。

对于主线开发来说，优点就是比较简单，不用处理分支合并，但是对人员素质要求 **非常高**，否则VCS日志里面会充斥着
各种混乱的记录，若有持续集成的话，主线更是会高频率的回退。

分支开发优点比较多，但是其集成频率天然的就比主线开发要低，合并难度自然要大一些。若代码架构上未做好解耦，各个模块职责
不够单一，那么分支开发造成的合并噩梦甚至可以直接干掉一个项目。

=== 在哪发布？

我们的发布相信各位已经很熟悉了，人肉封板，吼一声封板了，从主线clone一份代码，打包做镜像上传发邮件。这里从主线clone代码，
就是主线发布。相对的，还有分支发布，即每次发布时拉一个分支，然后从分支clone代码。

当然，正规地主线发布还会在主线上打一个Tag，不过我们的人肉封板勉强也起了Tag的作用吧。

NOTE: 后续的发布流程太简（ruo）单（zhi）了，到持续发布章节再讨论


那么，主线发布有什么问题？对于大多数的互联网公司，客户用的都是他们的最新版本（比如你永远用的淘宝的最新版本），
这时主线发布就是最好的选择，因为不用考虑维护历史版本的问题。

但是，对于我们这种传统企业，同时维护多个版本的局面是一定会存在的，那么分支发布显然更合适。不妨回忆一下，某个
局点还用的七八个版本之前的版本，这个时候出问题了要hotfix，而这个hotfix在某个员工自己的电脑上，几个月之后
别人又出问题了，又要hotfix，这个时候从哪找版本的代码？

=== 预发布

在讲预发布之前，先明确Profile的概念。简单来讲，Profile是一组配置，例如log级别，注入实例配置等。
显然对于不同环境，应该有不同的Profile。对于测试来说，可以不管开销，将log级别开到warning甚至debug，
还能预留调试窗口等等。但是对于局点来说，就不能完全不管开销，预留调试窗口也会被认为是存在安全风险的操作。

NOTE: log级别仅仅是个例子，大量的打日志但没有对应的约束、分析方法、分析工具的话，就等于没打。

这样一来，预发布的概念就比较简单了。就拿我们举例，我们对测试发布版本，应该是发布到pre-production分支，
测试验收完毕后，再发布到production分支，这两个分支的发布流程显然是不一样的。

同理，还能有pre-pre-production分支，就看要弄多少层缓冲了。

== 如何选择分支模型

如果有认真看完上面的内容，那么这个问题就不难回答了。

首先确认人员的水平，如果都是新手，那么主线开发显然是
不靠谱的。你问我代码架构严重耦合又都是新手咋办？那就只能主线开发，同时不要持续集成，能做多久是多久了。。。

然后确定项目类型，是library还是application？是application的话是否需要维护历史版本？对我们来说，SDK显然
就是library，moss就是application，并且需要维护历史版本。

NOTE: library相关的内容在构建章节再讲

最后，再确定验收流程，既有多少组织验收产品？这就决定了要不要预发布，或者几层预发布。

== 思考

按照上面的框架，git-flow是什么模型？github-flow呢？
