= 依赖注入

== 前言
上一篇主要讨论了单一实现的情况，这篇主要讨论多实现。

解决多实现问题最直接的想法就是基于XML的依赖注入，其灵活性是最强大的。但是由于可维护性、生态缺失等原因，此处不考虑基于XML的依赖注入。

== Qualifier

上文说过，``Type``和``Qualifier``组成的组合索引可以唯一确定一个Bean。在注入依赖时，类型信息以及有了，那么只需要再加上``Qualifier``就能完成Bean的选择。举个例子，依然是``UploadService``

[source,java]
----
public class RealUploadService implements UploadService {

  @Inject
  private final Repository repo;

  @Inject
  private final Writer writer;

  boolean upload(MetaData metaData, File file) {
    
    //business logic...
    
    return writer.write(file) && repo.write(metaData);
  }
}
----

在上一篇中这样注入没问题，因为``Repository``和``Writer``都只有一个实现，但是现在我要写单元测试了，新增了``MockRepository``和``MockWriter``实现，这样就无法确认要注入的Bean。这个时候，我可以给两种实现分别加上限定符：

[source,java]
----
@UnitTest
public class MockRepository implements Repository {

  boolean write(MetaData metaData) {
    return true;
  }
}
----

[source,java]
----
@Product
public class MockRepository implements Repository {
    
  boolean write(MetaData metaData) {
    return true;
  }
}
----

然后修改注入点：

[source,java]
----
public class RealUploadService implements UploadService {

  @Inject @Product                     // <1>
  private final Repository repo;

  @Inject @Product                    
  private final Writer writer;

  boolean upload(MetaData metaData, File file) {
    
    //business logic...
    
    return writer.write(file) && repo.write(metaData);
  }
}
----
<1> 新增限定符注解。

即可完成正确的依赖注入。

== Profiler
现在生成环境可以正常注入了，但是测试怎么写？我需要把所有的``@Product``注解换成``@UnitTest``注解，然后才能测试，测试完毕后还要换回去，这是不是太麻烦了？

NOTE: 这里举这个例子只是方便理解，其实还能通过``Mock``和``Stub``完成单元测试，具体操作自行阅读单元测试相关书籍。

现在，我希望能不修改代码，仅通过编译时的一些参数，就能完成所有的或者 *部分* Bean的替换，所以这里引入``Profiler``的概念。

``Profiler``代表了一组Bean，


== 总结

=== Bean 应该包含的属性

==== 检索
首先，Bean应该拥有一个唯一的``Id``或者``Name``，用于唯一确定一个Bean。这个``Id``可以理解为主键。其次，一个Bean会有一个或多个``Type``，以及一个或多个``Qualifier``。``Type``和``Qualifier``可以理解为两个索引，也就是说可以通过这两个属性来检索出一系列Bean。但是，``Type`` + ``Qualifier`` 则是唯一组合索引，只能检索出唯一的Bean。

===== 处理泛型


==== 实例化
要实例化一个Bean，首先就得知道这个Bean依赖的Bean，所以``Dependency``是一个必须的属性。然后，需要有一个``Provider``去实际的执行实例化操作。最后，``Scope``决定了什么时候实例化，什么时候复用之前的实例，即执行实例化操作的时机。

==== 回调
回调包括自身的生命周期回调和其余Bean注册的回调，这两种可以统一到``Lifecycle``属性中。

==== 可执行的Bean


=== IoC容器应该具有的功能

==== 检索Bean或者Bean的实例

==== 实例化Bean

==== 加载Bean

==== 刷新

==== 拓展点
//TODO

